---
name: rpi_artix7_star_tracker
board: boards/mars_zx3
version: 0.1.1

cores:
  - fpga/cores/axi_ctl_register_v1_0
  - fpga/cores/axi_sts_register_v1_0
  - fpga/cores/dna_reader_v1_0

memory:
  - name: control
    offset: '0x00'
    range: 32K
  - name: status
    offset: '0x20'
    range: 32K

control_registers:
  - counter_load[3]
  - counter_max[3]
  - cmdcontrol[3]
  - cmdduration[3]
  - trackctrl[3]
  - cmdtick[3]
  - backlash_tick[3]
  - backlash_duration[3]
  - led
  - led_pwm
  - camera_trigger
  - pec_calib_data
  - tmc_select
  - encoder_position

status_registers:
  - step_count[3]
  - status[3]
  - forty_two
  - pec_data_readback
  - encoder_position_readback
  - iic_encoder
    
parameters:
  fclk0: 50000000 # FPGA clock speed in Hz
  focuser_id: 2 # FPGA clock speed in Hz

xdc:
  - ./../../../boards/mars_zx3/config/ports.xdc 
  - ./constraints.xdc

drivers:
  - ./drivers/common.hpp
  - ./drivers/motor_driver.hpp
  - ./drivers/sky-tracker.hpp
  - ./drivers/ascom_interface.hpp
  - ./drivers/focuser.hpp
  - ./drivers/camera.hpp

web:
  - ./web/index.html
  - web/koheron.ts
  - web/led-blinker.ts
  - ./web/app.ts
  - web/main.css
