#
#  GitLab CI configuration file for koheron driver
#
#  R. Sarwar
#
#  UKAEA
#  20/08/19
#
#-----------------------------------------------------

# List of build stages

stages:
  - pages

# Pages
#------

pages:
  before_script:
    - "export LOGNAME=root"
  when: on_success
  stage: pages
  script:
   - pwd
   - apt-get update
   - apt install -y g++-5 cmake g++-5-multilib 
   - mkdir build
   - cd build
   - CXX=g++-5 cmake ../.
   - make VERBOSE=1
   - ls -alh
   - cd ..
   - cp build public -r
  artifacts:
    paths:
    - public
