set_property -dict {PACKAGE_PIN N11 IOSTANDARD LVCMOS33} [get_ports FPGA_CLK0_50]
create_clock -period 20.000 -name sys_clk_pin -waveform {0.000 10.000} -add [get_ports FPGA_CLK0_50]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list {CLOCKS_OBUF[1]}]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 30 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/target_counter_int[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[29]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[30]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_tack[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 30 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/issue_speed[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 30 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_track_speed[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 30 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_speed_buf[0][29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 3 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_mode_out[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_mode_out[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/current_mode_out[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 30 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_tracktick_in[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 32 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[29]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[30]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_tack[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 30 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/issue_speed[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 30 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_track_speed[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 30 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_stepper_counter[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 30 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_speed_buf[0][29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 3 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_mode_out[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_mode_out[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/current_mode_out[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 30 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_tracktick_in[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 30 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/target_counter_int[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 32 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[29]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[30]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_tack[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 30 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/issue_speed[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 30 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_track_speed[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 30 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_stepper_counter[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 30 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 3 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_mode_out[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_mode_out[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_mode_out[2]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 30 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[29]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_track_enabled_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_track_direction_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/use_acceleration]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/use_acceleration_track]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/done_acceleration_track]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/done_acceleration]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/use_acceleration]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_track_enabled_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/ctr_track_direction_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/use_acceleration_track]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/done_acceleration_track]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_FC/done_acceleration]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/use_acceleration_track]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/use_acceleration]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_track_enabled_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/ctr_track_direction_in]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/done_acceleration]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_DE/done_acceleration_track]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets CLOCKS_OBUF[1]]
