




create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list clock_150]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 32 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {SKYTRACKER.U_SKYTRACKER/sts_read_data[0]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[1]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[2]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[3]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[4]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[5]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[6]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[7]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[8]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[9]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[10]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[11]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[12]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[13]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[14]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[15]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[16]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[17]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[18]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[19]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[20]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[21]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[22]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[23]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[24]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[25]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[26]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[27]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[28]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[29]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[30]} {SKYTRACKER.U_SKYTRACKER/sts_read_data[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 32 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {SKYTRACKER.U_SKYTRACKER/pec_calib[0]} {SKYTRACKER.U_SKYTRACKER/pec_calib[1]} {SKYTRACKER.U_SKYTRACKER/pec_calib[2]} {SKYTRACKER.U_SKYTRACKER/pec_calib[3]} {SKYTRACKER.U_SKYTRACKER/pec_calib[4]} {SKYTRACKER.U_SKYTRACKER/pec_calib[5]} {SKYTRACKER.U_SKYTRACKER/pec_calib[6]} {SKYTRACKER.U_SKYTRACKER/pec_calib[7]} {SKYTRACKER.U_SKYTRACKER/pec_calib[8]} {SKYTRACKER.U_SKYTRACKER/pec_calib[9]} {SKYTRACKER.U_SKYTRACKER/pec_calib[10]} {SKYTRACKER.U_SKYTRACKER/pec_calib[11]} {SKYTRACKER.U_SKYTRACKER/pec_calib[12]} {SKYTRACKER.U_SKYTRACKER/pec_calib[13]} {SKYTRACKER.U_SKYTRACKER/pec_calib[14]} {SKYTRACKER.U_SKYTRACKER/pec_calib[15]} {SKYTRACKER.U_SKYTRACKER/pec_calib[16]} {SKYTRACKER.U_SKYTRACKER/pec_calib[17]} {SKYTRACKER.U_SKYTRACKER/pec_calib[18]} {SKYTRACKER.U_SKYTRACKER/pec_calib[19]} {SKYTRACKER.U_SKYTRACKER/pec_calib[20]} {SKYTRACKER.U_SKYTRACKER/pec_calib[21]} {SKYTRACKER.U_SKYTRACKER/pec_calib[22]} {SKYTRACKER.U_SKYTRACKER/pec_calib[23]} {SKYTRACKER.U_SKYTRACKER/pec_calib[24]} {SKYTRACKER.U_SKYTRACKER/pec_calib[25]} {SKYTRACKER.U_SKYTRACKER/pec_calib[26]} {SKYTRACKER.U_SKYTRACKER/pec_calib[27]} {SKYTRACKER.U_SKYTRACKER/pec_calib[28]} {SKYTRACKER.U_SKYTRACKER/pec_calib[29]} {SKYTRACKER.U_SKYTRACKER/pec_calib[30]} {SKYTRACKER.U_SKYTRACKER/pec_calib[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 4 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {SKYTRACKER.U_SKYTRACKER/iic_encoder_status[0]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_status[1]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_status[2]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_status[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 12 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[0]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[1]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[2]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[3]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[4]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[5]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[6]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[7]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[8]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[9]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[10]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position[11]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 5 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {SKYTRACKER.U_SKYTRACKER/ctrl_address[0]} {SKYTRACKER.U_SKYTRACKER/ctrl_address[1]} {SKYTRACKER.U_SKYTRACKER/ctrl_address[2]} {SKYTRACKER.U_SKYTRACKER/ctrl_address[3]} {SKYTRACKER.U_SKYTRACKER/ctrl_address[4]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 1 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list SKYTRACKER.U_SKYTRACKER/sts_bus_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 1 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list SKYTRACKER.U_SKYTRACKER/ctrl_rw]]
create_debug_core u_ila_1 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_1]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_1]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_1]
set_property C_DATA_DEPTH 2048 [get_debug_cores u_ila_1]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_1]
set_property C_INPUT_PIPE_STAGES 2 [get_debug_cores u_ila_1]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_1]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_1]
set_property port_width 1 [get_debug_ports u_ila_1/clk]
connect_debug_port u_ila_1/clk [get_nets [list clock_50]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe0]
set_property port_width 30 [get_debug_ports u_ila_1/probe0]
connect_debug_port u_ila_1/probe0 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/current_speed_buf[0][29]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe1]
set_property port_width 30 [get_debug_ports u_ila_1/probe1]
connect_debug_port u_ila_1/probe1 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_tracktick_in[29]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe2]
set_property port_width 30 [get_debug_ports u_ila_1/probe2]
connect_debug_port u_ila_1/probe2 [get_nets [list {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[0]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[1]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[2]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[3]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[4]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[5]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[6]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[7]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[8]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[9]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[10]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[11]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[12]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[13]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[14]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[15]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[16]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[17]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[18]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[19]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[20]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[21]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[22]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[23]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[24]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[25]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[26]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[27]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[28]} {SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/counter_buf[29]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe3]
set_property port_width 32 [get_debug_ports u_ila_1/probe3]
connect_debug_port u_ila_1/probe3 [get_nets [list {SKYTRACKER.U_SKYTRACKER/pec_data_synced[0]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[1]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[2]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[3]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[4]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[5]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[6]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[7]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[8]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[9]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[10]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[11]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[12]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[13]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[14]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[15]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[16]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[17]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[18]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[19]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[20]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[21]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[22]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[23]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[24]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[25]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[26]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[27]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[28]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[29]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[30]} {SKYTRACKER.U_SKYTRACKER/pec_data_synced[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe4]
set_property port_width 32 [get_debug_ports u_ila_1/probe4]
connect_debug_port u_ila_1/probe4 [get_nets [list {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[0]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[1]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[2]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[3]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[4]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[5]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[6]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[7]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[8]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[9]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[10]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[11]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[12]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[13]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[14]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[15]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[16]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[17]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[18]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[19]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[20]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[21]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[22]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[23]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[24]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[25]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[26]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[27]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[28]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[29]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[30]} {SKYTRACKER.U_SKYTRACKER/iic_encoder_position_synced[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe5]
set_property port_width 32 [get_debug_ports u_ila_1/probe5]
connect_debug_port u_ila_1/probe5 [get_nets [list {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[0]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[1]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[2]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[3]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[4]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[5]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[6]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[7]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[8]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[9]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[10]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[11]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[12]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[13]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[14]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[15]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[16]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[17]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[18]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[19]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[20]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[21]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[22]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[23]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[24]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[25]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[26]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[27]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[28]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[29]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[30]} {SKYTRACKER.U_SKYTRACKER/encoder_position_mux[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe6]
set_property port_width 32 [get_debug_ports u_ila_1/probe6]
connect_debug_port u_ila_1/probe6 [get_nets [list {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[0]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[1]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[2]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[3]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[4]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[5]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[6]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[7]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[8]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[9]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[10]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[11]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[12]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[13]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[14]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[15]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[16]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[17]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[18]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[19]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[20]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[21]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[22]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[23]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[24]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[25]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[26]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[27]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[28]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[29]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[30]} {SKYTRACKER.U_SKYTRACKER/encoder_position_synced[31]}]]
create_debug_port u_ila_1 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_1/probe7]
set_property port_width 1 [get_debug_ports u_ila_1/probe7]
connect_debug_port u_ila_1/probe7 [get_nets [list SKYTRACKER.U_SKYTRACKER/drv_ips.DRV_RA/ctr_track_enabled_in]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets clock_50]
